This commit was manufactured by cvs2svn to create tag 'InitialRelease'.

diff --git a/nuttx/arch/arm/src/Makefile b/nuttx/arch/arm/src/Makefile
--- a/nuttx/arch/arm/src/Makefile
+++ b/nuttx/arch/arm/src/Makefile
@@ -1,7 +1,7 @@
 ############################################################################
-# arch/arm/src/Makefile
+# Makefile
 #
-#   Copyright (C) 2007, 2008 Gregory Nutt. All rights reserved.
+#   Copyright (C) 2007 Gregory Nutt. All rights reserved.
 #   Author: Gregory Nutt <spudmonkey@racsa.co.cr>
 #
 # Redistribution and use in source and binary forms, with or without
@@ -14,7 +14,7 @@
 #    notice, this list of conditions and the following disclaimer in
 #    the documentation and/or other materials provided with the
 #    distribution.
-# 3. Neither the name NuttX nor the names of its contributors may be
+# 3. Neither the name Gregory Nutt nor the names of its contributors may be
 #    used to endorse or promote products derived from this software
 #    without specific prior written permission.
 #
@@ -36,6 +36,7 @@
 -include $(TOPDIR)/Make.defs
 -include chip/Make.defs
 
+MKDEP 		= $(TOPDIR)/tools/mkdeps.sh
 ARCH_SRCDIR	= $(TOPDIR)/arch/$(CONFIG_ARCH)/src
 CFLAGS		+= -I$(ARCH_SRCDIR)/chip -I$(ARCH_SRCDIR)/common -I$(TOPDIR)/sched
 
@@ -66,28 +67,23 @@ VPATH		= chip:common
 all: $(HEAD_OBJ) libarch$(LIBEXT)
 
 $(AOBJS) $(HEAD_AOBJ): %$(OBJEXT): %.S
-	$(call ASSEMBLE, $<, $@)
+	$(CC) -c $(CFLAGS) -D__ASSEMBLY__ $< -o $@
 
 $(COBJS): %$(OBJEXT): %.c
-	$(call COMPILE, $<, $@)
+	$(CC) -c $(CFLAGS) $< -o $@
 
 libarch$(LIBEXT): $(OBJS)
 	@( for obj in $(OBJS) ; do \
-		$(call ARCHIVE, $@, $${obj}); \
+		$(AR) $@ $${obj} || \
+			{ echo "$(AR) $@ $obj FAILED!" ; exit 1 ; } ; \
 	done ; )
 
 board/libboard$(LIBEXT):
-	$(MAKE) -C board TOPDIR="$(TOPDIR)" libboard$(LIBEXT)
+	$(MAKE) -C board TOPDIR=$(TOPDIR) libboard$(LIBEXT)
 
 nuttx: $(HEAD_AOBJ) board/libboard$(LIBEXT)
-	@echo "LD: nuttx"
-	@$(LD) --entry=__start $(LDFLAGS) $(LDPATHES) -L$(BOARDDIR) -o $(TOPDIR)/$@ $(HEAD_AOBJ) \
-		--start-group $(LDLIBS) -lboard --end-group $(EXTRA_LIBS) $(LIBGCC)
-ifeq ($(CONFIG_BOOT_RUNFROMFLASH),y)
-	@export flashloc=`$(OBJDUMP) --all-headers $(TOPDIR)/$@ | grep _eronly | cut -d' ' -f1`;  \
-	$(OBJCOPY) --adjust-section-vma=.data=0x$$flashloc $(TOPDIR)/$@ $(TOPDIR)/$@.flashimage
-	@mv $(TOPDIR)/$@.flashimage $(TOPDIR)/$@
-endif
+	$(LD) --entry=__start $(LDFLAGS) $(LDPATHES) -L$(BOARDDIR) -o $(TOPDIR)/$@ $(HEAD_AOBJ) \
+		--start-group $(LDLIBS) -lboard --end-group $(EXTRA_LIBS) $(LIBGCC) 
 	@$(NM) $(TOPDIR)/$@ | \
 	grep -v '\(compiled\)\|\(\$(OBJEXT)$$\)\|\( [aUw] \)\|\(\.\.ng$$\)\|\(LASH[RL]DI\)' | \
 	sort > $(TOPDIR)/System.map
@@ -96,26 +92,32 @@ endif
 		$(OBJCOPY) --adjust-section-vma=.vector=0x$$vflashstart $(TOPDIR)/$@ $(TOPDIR)/$@.flashimage; \
 		mv $(TOPDIR)/$@.flashimage $(TOPDIR)/$@; \
 	fi
-
-.depend: Makefile chip/Make.defs $(SRCS)
-	@if [ -e board/Makefile ]; then \
-		$(MAKE) -C board TOPDIR="$(TOPDIR)" depend ; \
+ifeq ($(CONFIG_RRLOAD_BINARY),y)
+	@$(TOPDIR)/tools/mkimage.sh --Prefix $(CROSSDEV) $(TOPDIR)/$@ $(TOPDIR)/$@.rr
+	@if [ -w /tftpboot ] ; then \
+		cp -f $(TOPDIR)/$@.rr /tftpboot/$@.rr.${CONFIG_ARCH}; \
 	fi
-	@$(MKDEP) --dep-path chip --dep-path common $(CC) -- $(CFLAGS) -- $(SRCS) >Make.dep
+endif
+
+.depend: Makefile $(SRCS)
+	@if [ -e board/Makefile ]; then \
+		$(MAKE) -C board TOPDIR=$(TOPDIR) depend ; \
+	if
+	$(MKDEP) $(CC) -- $(CFLAGS) -- $(SRCS) >Make.dep
 	@touch $@
 
 depend: .depend
 
 clean:
 	@if [ -e board/Makefile ]; then \
-		$(MAKE) -C board TOPDIR="$(TOPDIR)" clean ; \
+		$(MAKE) -C board TOPDIR=$(TOPDIR) clean ; \
 	fi
-	@rm -f libarch$(LIBEXT) *~ .*.swp
-	$(call CLEAN)
+	@rm -f libarch$(LIBEXT) *~
+	@if [ ! -z "$(OBJEXT)" ]; then rm -f *$(OBJEXT); fi
 
 distclean: clean
 	@if [ -e board/Makefile ]; then \
-		$(MAKE) -C board TOPDIR="$(TOPDIR)" distclean ; \
+		$(MAKE) -C board TOPDIR=$(TOPDIR) distclean ; \
 	fi
 	@rm -f Make.dep .depend
 
diff --git a/nuttx/arch/z16/src/Makefile b/nuttx/arch/z16/src/Makefile
--- a/nuttx/arch/z16/src/Makefile
+++ b/nuttx/arch/z16/src/Makefile
@@ -36,106 +36,74 @@
 -include $(TOPDIR)/Make.defs
 -include chip/Make.defs
 
-COMPILER	= ${shell basename $(CC)}
-ARCHSRCDIR	= $(TOPDIR)/arch/$(CONFIG_ARCH)/src
-ifeq ($(COMPILER),zneocc.exe)
-WARCHSRCDIR	:= ${shell cygpath -w $(ARCHSRCDIR)}
-USRINCLUDES	= -usrinc:'.;$(WTOPDIR)\sched;$(WARCHSRCDIR);$(WARCHSRCDIR)\common'
-else
-WARCHSRCDIR	= $(ARCHSRCDIR)
-USRINCLUDES	= -I$(TOPDIR)/sched -I$(ARCHSRCDIR) -I$(ARCHSRCDIR)/common
-endif
-INCLUDES	= $(ARCHSTDINCLUDES) $(USRINCLUDES)
-CFLAGS		= $(ARCHWARNINGS) $(ARCHOPTIMIZATION) $(ARCHCPUFLAGS) $(INCLUDES) $(ARCHDEFINES)
-CPPFLAGS	+= -I$(ARCHSRCDIR)
-ifeq ($(COMPILER),zneocc.exe)
-LDFLAGS 	= @"${shell cygpath -w $(ARCHSRCDIR)/nuttx.linkcmd}"
-endif
+MKDEP 		= $(TOPDIR)/tools/mkdeps.sh
+ARCH_SRCDIR	= $(TOPDIR)/arch/$(CONFIG_ARCH)/src
+CFLAGS		+= -I$(ARCH_SRCDIR)/chip -I$(ARCH_SRCDIR)/common -I$(TOPDIR)/sched
 
-HEAD_ASRC	= $(HEAD_SSRC:.S=$(ASMEXT))
-HEAD_AOBJ	= $(HEAD_SSRC:.S=$(OBJEXT))
+HEAD_AOBJ	= $(HEAD_ASRC:.S=$(OBJEXT))
 
-SSRCS		= $(CHIP_SSRCS) $(CMN_SSRCS)
-ASRCS		= $(SSRCS:.S=$(ASMEXT))
-AOBJS		= $(SSRCS:.S=$(OBJEXT))
+ASRCS		= $(CHIP_ASRCS) $(CMN_ASRCS)
+AOBJS		= $(ASRCS:.S=$(OBJEXT))
 
 CSRCS		= $(CHIP_CSRCS) $(CMN_CSRCS)
 COBJS		= $(CSRCS:.c=$(OBJEXT))
 
-DEPSRCS 	= $(SSRCS) $(CSRCS)
+SRCS		= $(ASRCS) $(CSRCS)
 OBJS		= $(AOBJS) $(COBJS)
 
+LDFLAGS		= $(ARCHSCRIPT)
+EXTRA_LIBS	=
+
+LINKLIBS	=
+LDPATHES	= $(addprefix -L$(TOPDIR)/,$(dir $(LINKLIBS)))
+LDLIBS		= $(patsubst lib%,-l%,$(basename $(notdir $(LINKLIBS))))
+
 BOARDDIR	= $(TOPDIR)/arch/$(CONFIG_ARCH)/src/board
+
+LIBGCC		= ${shell $(CC) -print-libgcc-file-name}
 
 VPATH		= chip:common
 
 all: $(HEAD_OBJ) libarch$(LIBEXT)
 
-ifeq ($(COMPILER),zneocc.exe)
-$(ASRCS) $(HEAD_ASRC): %$(ASMEXT): %.S
-	@$(CPP) $(CPPFLAGS) $< -o $@.tmp
-	@cat $@.tmp | sed -e "s/^#/;/g" > $@
-	@rm $@.tmp
-
-$(AOBJS) $(HEAD_AOBJ): %$(OBJEXT): %$(ASMEXT)
-	$(call ASSEMBLE, $<, $@)
-else
-$(OBJS) $(HEAD_AOBJ): %$(OBJEXT): %.S
-	$(call ASSEMBLE, $<, $@)
-endif
+$(AOBJS) $(HEAD_AOBJ): %$(OBJEXT): %.S
+	$(CC) -c $(CFLAGS) -D__ASSEMBLY__ $< -o $@
 
 $(COBJS): %$(OBJEXT): %.c
-	$(call COMPILE, $<, $@)
+	$(CC) -c $(CFLAGS) $< -o $@
 
 libarch$(LIBEXT): $(OBJS)
 	@( for obj in $(OBJS) ; do \
-		$(call ARCHIVE, $@, $${obj}); \
+		$(AR) $@ $${obj} || \
+			{ echo "$(AR) $@ $obj FAILED!" ; exit 1 ; } ; \
 	done ; )
 
 board/libboard$(LIBEXT):
-	@$(MAKE) -C board TOPDIR="$(TOPDIR)" libboard$(LIBEXT)
+	$(MAKE) -C board TOPDIR=$(TOPDIR) libboard$(LIBEXT)
 
-ifeq ($(COMPILER),zneocc.exe)
-nuttx.linkcmd: $(LINKCMDTEMPLATE)
-	@cp -f $(LINKCMDTEMPLATE) nuttx.linkcmd
-	@echo "\"${shell cygpath -w $(TOPDIR)/nuttx}\"= \\" >>nuttx.linkcmd
-	@echo "  \"${shell cygpath -w $(ARCHSRCDIR)/$(HEAD_AOBJ)}\", \\" >>nuttx.linkcmd
-	@( for lib in $(LINKLIBS); do \
-		echo "  \"`cygpath -w $(TOPDIR)/$${lib}`\", \\" >>nuttx.linkcmd; \
-	done ; )
-	@echo "  \"${shell cygpath -w $(ARCHSRCDIR)/board/libboard$(LIBEXT)}\", \\"  >>nuttx.linkcmd
-	@echo "  \"${shell cygpath -w $(ZDSSTDLIBDIR)/chelpld$(LIBEXT)}\", \\"  >>nuttx.linkcmd
-	@echo "  \"${shell cygpath -w $(ZDSSTDLIBDIR)/fpld$(LIBEXT)}\""  >>nuttx.linkcmd
-else
-nuttx.linkcmd:
-endif
+nuttx: $(HEAD_AOBJ) board/libboard$(LIBEXT)
+	$(LD) --entry=__start $(LDFLAGS) $(LDPATHES) -L$(BOARDDIR) -o $(TOPDIR)/$@ $(HEAD_AOBJ) \
+		--start-group $(LDLIBS) -lboard --end-group $(EXTRA_LIBS) $(LIBGCC) 
 
-nuttx$(EXEEXT): $(HEAD_AOBJ) board/libboard$(LIBEXT) nuttx.linkcmd
-	@echo "LD:  nuttx.hex"
-	@$(LD) $(LDFLAGS)
-
-.depend: Makefile chip/Make.defs $(DEPSRCS)
+.depend: Makefile chip/Make.defs $(SRCS)
 	@if [ -e board/Makefile ]; then \
-		$(MAKE) -C board TOPDIR="$(TOPDIR)" depend ; \
+		$(MAKE) -C board TOPDIR=$(TOPDIR) depend ; \
 	fi
-	@$(MKDEP) --dep-path chip --dep-path common $(CC) -- $(CFLAGS) -- $(DEPSRCS) >Make.dep
+	$(MKDEP) --dep-path chip --dep-path common $(CC) -- $(CFLAGS) -- $(SRCS) >Make.dep
 	@touch $@
 
 depend: .depend
 
 clean:
 	@if [ -e board/Makefile ]; then \
-		$(MAKE) -C board TOPDIR="$(TOPDIR)" clean ; \
+		$(MAKE) -C board TOPDIR=$(TOPDIR) clean ; \
 	fi
-	@rm -f libarch$(LIBEXT) *~ .*.swp
-ifeq ($(COMPILER),zneocc.exe)
-	@rm -f nuttx.linkcmd *.asm *.tmp *.map
-endif
-	$(call CLEAN)
+	@rm -f libarch$(LIBEXT) *~
+	@if [ ! -z "$(OBJEXT)" ]; then rm -f *$(OBJEXT); fi
 
 distclean: clean
 	@if [ -e board/Makefile ]; then \
-		$(MAKE) -C board TOPDIR="$(TOPDIR)" distclean ; \
+		$(MAKE) -C board TOPDIR=$(TOPDIR) distclean ; \
 	fi
 	@rm -f Make.dep .depend
 
diff --git a/nuttx/arch/z80/src/Makefile b/nuttx/arch/z80/src/Makefile
--- a/nuttx/arch/z80/src/Makefile
+++ b/nuttx/arch/z80/src/Makefile
@@ -38,13 +38,183 @@
 
 -include $(TOPDIR)/Make.defs
 -include chip/Make.defs
--include board/Make.defs
 
 ############################################################################
-# Compiler-Dependent Make
-COMPILER	= ${shell basename $(CC)}
-ifeq ($(COMPILER),sdcc)
-include Makefile.sdcc
-else
-include Makefile.zdsii
-endif
+# Tools
+
+MKDEP 		= $(TOPDIR)/tools/mkdeps.sh
+
+CFLAGS		+= -I$(ARCH_SRCDIR)/chip -I$(ARCH_SRCDIR)/common -I$(TOPDIR)/sched
+LDFLAGS		= $(ARCHSCRIPT)
+
+LDPATHES	= $(addprefix -L$(TOPDIR)/,$(dir $(LINKLIBS)))
+LDLIBS		= $(patsubst lib%,-l%,$(basename $(notdir $(LINKLIBS))))
+
+CPPFLAGS	= $(ARCHINCLUDES) $(ARCHDEFINES) -D__ASSEMBLY__
+
+############################################################################
+# Files and directories
+
+# There should be one head source (.asm file)
+
+HEAD_AOBJ	= $(HEAD_ASRC:$(ASMEXT)=$(OBJEXT))
+
+# Assembly sources and objects
+
+ASRCS		= $(CHIP_ASRCS) $(CMN_ASRCS)
+AOBJS		= $(ASRCS:.S=$(OBJEXT))
+
+# C sources and objects
+
+CSRCS		= $(CHIP_CSRCS) $(CMN_CSRCS)
+COBJS		= $(CSRCS:.c=$(OBJEXT))
+
+# All sources and objcts
+
+SRCS		= $(ASRCS) $(CSRCS)
+OBJS		= $(AOBJS) $(COBJS)
+
+# Sources and objects for the test target (plus HEAD_AOBJ
+
+TEST_AOBJS	= $(TEST_ASRCS:$(ASMEXT)=$(OBJEXT))
+TEST_COBJS	= $(TEST_CSRCS:.c=$(OBJEXT))
+
+TESTSRCS	= up_irqtest.c
+TESTOBJS	= $(TESTSRCS:.c=$(OBJEXT))
+TESTEXTRAOBJS	= up_savecontext$(OBJEXT) up_restorecontext$(OBJEXT)
+
+# Sources that can have dependencies (no .asm files)
+
+DEPSRCS		= $(SRCS)
+
+# Directories
+
+ARCH_SRCDIR	= $(TOPDIR)/arch/$(CONFIG_ARCH)/src
+BOARDDIR	= $(TOPDIR)/arch/$(CONFIG_ARCH)/src/board
+
+VPATH		= chip:common
+
+# Libraries
+
+LIBGCC		= ${shell $(CC) -print-libgcc-file-name}
+
+# Supports dynamic sizing of HEAP
+
+HEAP_BASE	= ${shell \
+			if [ -e pass1.mem ]; then \
+				cat pass1.mem | grep "ROM/EPROM/FLASH" | \
+				sed -e "s/[ ][ ]*/ /g" | cut -d' ' -f4 ; \
+			else \
+				echo $(DEF_HEAP_BASE) ; \
+			fi \
+		   }
+
+STACK_BASE	= ${shell \
+			if [ -e pass1.mem ]; then \
+				cat pass1.mem | grep "Stack starts" | \
+				cut -d' ' -f4 ; \
+			else \
+				echo $(DEF_STACK_BASE) ; \
+			fi \
+		   }
+
+############################################################################
+# Targets
+
+all: $(HEAD_AOBJ) libarch$(LIBEXT)
+
+$(AOBJS) $(HEAD_AOBJ) $(TEST_AOBJS): %$(OBJEXT): %$(ASMEXT)
+	$(AS) $(ASFLAGS) $@ $<
+
+$(COBJS) $(TEST_COBJS): %$(OBJEXT): %.c
+	$(CC) -c $(CFLAGS) $< -o $@
+
+# Create a header file that contains addressing information needed by the code
+
+pass1.mem:
+
+up_mem.h: pass1.mem
+	@echo "#ifndef __ARCH_MEM_H" >up_mem.h
+	@echo "#define __ARCH_MEM_H" >>up_mem.h
+	@echo "" >>up_mem.h
+	@echo "#define UP_DEFAULT_STACK_BASE $(DEF_STACK_BASE)" >>up_mem.h
+	@echo "#define UP_DEFAULT_HEAP_BASE $(DEF_HEAP_BASE)" >> up_mem.h
+	@echo "" >>up_mem.h
+	@echo "#define UP_STACK_BASE         $(STACK_BASE)" >>up_mem.h
+	@echo "#if UP_STACK_BASE > UP_DEFAULT_STACK_BASE" >>up_mem.h
+	@echo "#  error \"Stack overlap:  $(DEF_STACK_BASE) < $(STACK_BASE)\""  >>up_mem.h
+	@echo "#elif UP_STACK_BASE < UP_DEFAULT_STACK_BASE" >>up_mem.h
+	@echo "#  warning \"Wasted stack: $(DEF_STACK_BASE) > $(STACK_BASE)\""  >>up_mem.h
+	@echo "#endif" >>up_mem.h
+	@echo "" >>up_mem.h
+	@echo "#define UP_HEAP_BASE          $(HEAP_BASE)" >> up_mem.h
+	@echo "#define UP_HEAP_END           $(CONFIG_DRAM_END)" >> up_mem.h
+	@echo "" >>up_mem.h
+	@echo "#endif /* __ARCH_MEM_H */" >>up_mem.h
+
+# Combine all objects in this directory into a library
+
+libarch$(LIBEXT): up_mem.h $(OBJS)
+	@( for obj in $(OBJS) ; do \
+		$(AR) $@ $${obj} || \
+			{ echo "$(AR) $@ $${obj} FAILED!" ; exit 1 ; } ; \
+	done ; )
+
+# This builds the libboard library in the board/ subdirectory 
+
+board/libboard$(LIBEXT):
+	$(MAKE) -C board TOPDIR=$(TOPDIR) libboard$(LIBEXT)
+
+# This target builds the final executable
+
+pass1.ihx: up_mem.h $(HEAD_AOBJ) board/libboard$(LIBEXT)
+	$(CC) $(LDFLAGS) -L$(BOARDDIR) $(SDCCPATH) $(HEAD_AOBJ) \
+		-llibboard$(LIBEXT) $(SDCCLIBS) -o $@
+	@rm -f up_mem.h
+	@rm -f up_allocateheap$(OBJEXT) libarch$(LIBEXT)
+	@$(MAKE) TOPDIR=$(TOPDIR) libarch$(LIBEXT)
+
+nuttx.ihx: up_mem.h $(HEAD_AOBJ)
+	$(CC) $(LDFLAGS) -L$(BOARDDIR) $(SDCCPATH) $(HEAD_AOBJ) \
+		-llibboard$(LIBEXT) $(SDCCLIBS) -o $@
+
+nuttx$(EXEEXT): pass1.ihx nuttx.ihx
+	@rm -f pass1.*
+	packihx nuttx.ihx > $(TOPDIR)/nuttx$(EXEEXT)
+	@cp -f nuttx.map $(TOPDIR)/.
+
+# This target builds a test program to verify interrupt context switching.  irqtest is
+# a PHONY target that just sets upt the up_irqtest build correctly
+
+up_irqtest.ihx: $(TEST_COBJS)
+	$(CC) $(LDFLAGS) -L. $(SDCCPATH) $(HEAD_AOBJ) $(TEST_COBJS) $(TESTEXTRAOBJS) $(SDCCLIBS) -o $@
+
+irqtest:
+	$(MAKE) TOPDIR=../../.. up_irqtest.ihx
+
+# Build dependencies
+
+.depend: Makefile up_mem.h chip/Make.defs $(DEPSRCS)
+	@if [ -e board/Makefile ]; then \
+		$(MAKE) -C board TOPDIR=$(TOPDIR) depend ; \
+	fi
+	$(MKDEP) --dep-path chip --dep-path common $(CC) -- $(CFLAGS) -- $(SRCS) >Make.dep
+	@touch $@
+
+depend: .depend
+
+clean:
+	@if [ -e board/Makefile ]; then \
+		$(MAKE) -C board TOPDIR=$(TOPDIR) clean ; \
+	fi
+	rm -f libarch$(LIBEXT) up_mem.h
+	rm -f *.asm *.rel *.lst *.rst *.sym *.adb *.lnk *.map *.mem *.ihx *.hex *~
+	if [ ! -z "$(OBJEXT)" ]; then rm -f *$(OBJEXT); fi
+
+distclean: clean
+	@if [ -e board/Makefile ]; then \
+		$(MAKE) -C board TOPDIR=$(TOPDIR) distclean ; \
+	fi
+	rm -f Make.dep .depend
+
+-include Make.dep
diff --git a/nuttx/configs/z16f2800100zcog/src/Makefile b/nuttx/configs/z16f2800100zcog/src/Makefile
--- a/nuttx/configs/z16f2800100zcog/src/Makefile
+++ b/nuttx/configs/z16f2800100zcog/src/Makefile
@@ -1,5 +1,5 @@
 ############################################################################
-# configs/z16f2800100zcog/Makefile
+# board/Makefile
 #
 #   Copyright (C) 2008 Gregory Nutt. All rights reserved.
 #   Author: Gregory Nutt <spudmonkey@racsa.co.cr>
@@ -35,50 +35,45 @@
 
 -include $(TOPDIR)/Make.defs
 
-ARCHSRCDIR	= $(TOPDIR)/arch/$(CONFIG_ARCH)/src
-WARCHSRCDIR	= ${shell cygpath -w $(ARCHSRCDIR)}
-USRINCLUDES	= -usrinc:'.;$(WTOPDIR)\sched;$(WARCHSRCDIR);$(WARCHSRCDIR)\common'
-INCLUDES	= $(ARCHSTDINCLUDES) $(USRINCLUDES)
-CFLAGS		= $(ARCHWARNINGS) $(ARCHOPTIMIZATION) $(ARCHCPUFLAGS) $(INCLUDES) $(ARCHDEFINES)
+MKDEP 		= $(TOPDIR)/tools/mkdeps.sh
+CFLAGS		+= -I$(TOPDIR)/sched
 
 ASRCS		= 
 AOBJS		= $(ASRCS:.S=$(OBJEXT))
-CSRCS		= z16f_lowinit.c z16f_leds.c
+CSRCS		= 
 COBJS		= $(CSRCS:.c=$(OBJEXT))
 
 SRCS		= $(ASRCS) $(CSRCS)
 OBJS		= $(AOBJS) $(COBJS)
 
+ARCH_SRCDIR	= $(TOPDIR)/arch/$(CONFIG_ARCH)/src
+CFLAGS		+= -I$(ARCH_SRCDIR)/chip -I$(ARCH_SRCDIR)/common
 
 all: libboard$(LIBEXT)
 
-$(ASRCS) $(HEAD_ASRC): %$(ASMEXT): %.S
-	@$(CPP) $(CPPFLAGS) $< -o $@.tmp
-	@cat $@.tmp | sed -e "s/^#/;/g" > $@
-	@rm $@.tmp
-
-$(AOBJS): %$(OBJEXT): %$(ASMEXT)
-	$(call ASSEMBLE, $<, $@)
+$(AOBJS): %$(OBJEXT): %.S
+	$(CC) -c $(CFLAGS) -D__ASSEMBLY__ $< -o $@
 
 $(COBJS) $(LINKOBJS): %$(OBJEXT): %.c
-	$(call COMPILE, $<, $@)
+	$(CC) -c $(CFLAGS) $< -o $@
 
 libboard$(LIBEXT): $(OBJS)
-	@( for obj in $(OBJS) ; do \
-		$(call ARCHIVE, $@, $${obj}); \
+	( for obj in $(OBJS) ; do \
+		$(AR) $@ $${obj} || \
+			{ echo "$(AR) $@ $obj FAILED!" ; exit 1 ; } ; \
 	done ; )
 
 .depend: Makefile $(SRCS)
-	@$(MKDEP) $(CC) -- $(CFLAGS) -- $(SRCS) >Make.dep
-	@touch $@
+	$(MKDEP) $(CC) -- $(CFLAGS) -- $(SRCS) >Make.dep
+	touch $@
 
 depend: .depend
 
 clean:
-	@rm -f libboard$(LIBEXT) *~ .*.swp
-	$(call CLEAN)
+	rm -f libboard$(LIBEXT) *~
+	if [ ! -z "$(OBJEXT)" ]; then rm -f *$(OBJEXT); fi
 
 distclean: clean
-	@rm -f Make.dep .depend
+	rm -f Make.dep .depend
 
 -include Make.dep
diff --git a/nuttx/configs/z80sim/src/Makefile b/nuttx/configs/z80sim/src/Makefile
--- a/nuttx/configs/z80sim/src/Makefile
+++ b/nuttx/configs/z80sim/src/Makefile
@@ -1,7 +1,7 @@
-############################################################################
-# configs/z80sim/src/Makefile
+############################################################
+# Makefile
 #
-#   Copyright (C) 2007, 2008 Gregory Nutt. All rights reserved.
+#   Copyright (C) 2007 Gregory Nutt. All rights reserved.
 #   Author: Gregory Nutt <spudmonkey@racsa.co.cr>
 #
 # Redistribution and use in source and binary forms, with or without
@@ -14,7 +14,7 @@
 #    notice, this list of conditions and the following disclaimer in
 #    the documentation and/or other materials provided with the
 #    distribution.
-# 3. Neither the name NuttX nor the names of its contributors may be
+# 3. Neither the name Gregory Nutt nor the names of its contributors may be
 #    used to endorse or promote products derived from this software
 #    without specific prior written permission.
 #
@@ -31,15 +31,16 @@
 # ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
 #
-############################################################################
+############################################################
 
 -include $(TOPDIR)/Make.defs
 
-CFLAGS		+= -I$(TOPDIR)/sched -I$(TOPDIR)/arch/z80/src/common -I$(TOPDIR)/arch/z80/src/z80
+MKDEP 		= $(TOPDIR)/tools/mkdeps.sh
+CFLAGS		+= -I$(TOPDIR)/sched
 
-ASRCS		= 
+ASRCS		= z80_lowputc$(ASMEXT) 
 AOBJS		= $(ASRCS:$(ASMEXT)=$(OBJEXT))
-CSRCS		= z80_irq.c z80_serial.c z80_timerisr.c z80_lowputc.c
+CSRCS		= z80_decodeirq.c z80_irq.c z80_serial.c z80_timerisr.c
 COBJS		= $(CSRCS:.c=$(OBJEXT))
 
 SRCS		= $(ASRCS) $(CSRCS)
@@ -50,27 +51,29 @@ CFLAGS		+= -I $(TOPDIR)/arch/$(CONFIG_ARCH)/src
 all: libboard$(LIBEXT)
 
 $(AOBJS): %$(OBJEXT): %$(ASMEXT)
-	$(call ASSEMBLE, $<, $@)
+	$(CC) -c $(CFLAGS) -D__ASSEMBLY__ $< -o $@
 
 $(COBJS) $(LINKOBJS): %$(OBJEXT): %.c
-	$(call COMPILE, $<, $@)
+	$(CC) -c $(CFLAGS) $< -o $@
 
 libboard$(LIBEXT): $(OBJS)
-	@( for obj in $(OBJS) ; do \
-		$(call ARCHIVE, $@, $${obj}); \
+	( for obj in $(OBJS) ; do \
+		$(AR) $@ $${obj} || \
+			{ echo "$(AR) $@ $obj FAILED!" ; exit 1 ; } ; \
 	done ; )
 
 .depend: Makefile $(SRCS)
-	@$(MKDEP) $(CC) -- $(CFLAGS) -- $(SRCS) >Make.dep
-	@touch $@
+	$(MKDEP) $(CC) -- $(CFLAGS) -- $(SRCS) >Make.dep
+	touch $@
 
 depend: .depend
 
 clean:
-	@rm -f libboard$(LIBEXT) *~ .*.swp
-	$(call CLEAN)
+	rm -f libboard$(LIBEXT)
+	rm -f *.asm *.rel *.lst *.rst *.sym *.adb *.lnk *.map *.mem *.ihx *.hex *~
+	if [ ! -z "$(OBJEXT)" ]; then rm -f *$(OBJEXT); fi
 
 distclean: clean
-	@rm -f Make.dep .depend
+	rm -f Make.dep .depend
 
 -include Make.dep
